### ISSUE TITLE
 Could not insert a bundleNeedsRemesh for entitybecause it doesn't exist

### ISSUE THREAD

**Issue by bbarker** [splashdust/bevy_voxel_world#14] opened 2023-12-09 12:43 UTC
I encountered a slightly different error from #12 , though possibly related:

```
thread 'main' panicked at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/mod.rs:1022:13:
error[B0003]: Could not insert a bundle (of type `bevy_voxel_world::chunk::NeedsRemesh`) for entity 2275v3 because it doesn't exist in this World.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic when applying buffers for system `bevy_voxel_world::voxel_world_internal::flush_voxel_write_buffer`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!

```

**Comment by splashdust** [comment] 2023-12-10 20:31
Hi @bbarker, thanks for reporting these issues!

I was able to recreate the issue, and I think it may have to do with system ordering in `bevy_voxel_world`. I've pushed a fix to the main branch, but it is hard to say for sure if the problem is fully solved, since it is so intermittent. Could you try and set your dependency version to the git repo and see if the problem seem to be fixed for you?

**Comment by bbarker** [comment] 2023-12-11 00:29
Thanks!

So far, I've still been able to reproduce the issue on the most recent commit to master (115bd34).

**Comment by splashdust** [comment] 2023-12-11 21:56
Just realised that Bevy has a `try_insert` command for these cases, which should fail silently if the entity does not exist. I pushed a new update to `main` using that. Give it another go and see if it's more stable now.

**Closed** 2023-12-18 20:08 UTC
Labels: bug
